# Generated by Django 4.2.7 on 2023-11-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
