# Generated by Django 4.2.7 on 2023-11-05 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_event_seat_eventimage_event_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
    ]
