# Generated by Django 4.2.7 on 2023-11-07 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_event_end_date_event_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatClass', models.CharField(max_length=1, unique=True)),
                ('totalSeat', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.PositiveIntegerField()),
                ('seatPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seatCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seatcategory')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.seatcategory'),
        ),
    ]
