# Generated by Django 4.2.7 on 2023-11-07 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seatcategory_seat_event_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seatcategory'),
        ),
    ]
