# Generated by Django 4.2.7 on 2023-11-07 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_event_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='seat',
        ),
        migrations.AddField(
            model_name='seatcategory',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seat_categories', to='accounts.event'),
            preserve_default=False,
        ),
    ]
