# Generated by Django 4.2.7 on 2023-11-09 01:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_seat_seatprice_seatcategory_seatprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatcategory',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='seatCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seat_categories', to='accounts.seatcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 11, 24)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 11, 9)),
        ),
    ]
