# Generated by Django 4.2.7 on 2023-11-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_seatcategory_event_event_seatcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='seatCategory',
        ),
        migrations.AddField(
            model_name='event',
            name='seatCategories',
            field=models.ManyToManyField(related_name='events', to='accounts.seatcategory'),
        ),
    ]
