# Generated by Django 4.2.7 on 2023-11-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_event_seatcategory_event_seatcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='seatCategories',
        ),
        migrations.AddField(
            model_name='event',
            name='seats',
            field=models.ManyToManyField(blank=True, related_name='events', to='accounts.seat'),
        ),
    ]
