# Generated by Django 4.2.7 on 2023-11-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_event_end_date_alter_event_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='eventImages',
            field=models.ManyToManyField(blank=True, related_name='events', to='accounts.eventimage'),
        ),
    ]
